defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  github.com/openshift-pipelines/tektoncd-pruner/cmd/controller: registry.access.redhat.com/ubi8/ubi-minimal
  github.com/openshift-pipelines/tektoncd-pruner/cmd/webhook: registry.access.redhat.com/ubi8/ubi-minimal

builds:
  - id: ko
    ldflags:
      - "{{ .Env.LDFLAGS }}"
