---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pruner-controller
  namespace: tekton-pipelines
  labels:
    pruner.tekton.dev/release: "devel"
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pruner
