apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pruner-controller
  namespace: tekton-pipelines
  labels:
    pruner.tekton.dev/release: "devel"
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pruner
subjects:
  - kind: ServiceAccount
    name: tekton-pruner-controller
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-pruner-controller
  apiGroup: rbac.authorization.k8s.io
