apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tektonpruners.pruner.tekton.dev
  labels:
    pruner.tekton.dev/release: "devel"
    knative.dev/crd-install: "true"
spec:
  group: pruner.tekton.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - ttlSecondsAfterFinished
                - successfulHistoryLimit
                - failedHistoryLimit
              properties:
                failedHistoryLimit:
                  type: integer
                  format: int32
                pipelines:
                  type: array
                  items:
                    type: object
                    required:
                      - ttlSecondsAfterFinished
                      - successfulHistoryLimit
                      - failedHistoryLimit
                    properties:
                      failedHistoryLimit:
                        type: integer
                        format: int32
                      name:
                        type: string
                      successfulHistoryLimit:
                        type: integer
                        format: int32
                      ttlSecondsAfterFinished:
                        type: integer
                        format: int32
                successfulHistoryLimit:
                  type: integer
                  format: int32
                tasks:
                  type: array
                  items:
                    type: object
                    required:
                      - ttlSecondsAfterFinished
                      - successfulHistoryLimit
                      - failedHistoryLimit
                    properties:
                      failedHistoryLimit:
                        type: integer
                        format: int32
                      name:
                        type: string
                      successfulHistoryLimit:
                        type: integer
                        format: int32
                      ttlSecondsAfterFinished:
                        type: integer
                        format: int32
                ttlSecondsAfterFinished:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                annotations:
                  description: Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                conditions:
                  description: Conditions the latest available observations of a resource's current state.
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant).
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      severity:
                        description: Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                observedGeneration:
                  description: ObservedGeneration is the 'Generation' of the Service that was last processed by the controller.
                  type: integer
                  format: int64
      additionalPrinterColumns:
        - name: Ready
          type: string
          jsonPath: ".status.conditions[?(@.type=='Ready')].status"
        - name: Reason
          type: string
          jsonPath: ".status.conditions[?(@.type=='Ready')].reason"
  names:
    kind: TektonPruner
    plural: tektonpruners
    singular: tektonpruner
    categories:
      - tekton
      - tekton-pruner
    shortNames:
      - tp
      - tps
  scope: Namespaced
