---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
    pruner.tekton.dev/release: "devel"
  name: tekton-pruner-webhook
  namespace: tekton-pipelines
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    role: webhook
