---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-pruner-default-spec
  namespace: default
data:
  _example: |
    ttlSecondsAfterFinished: 600 # 10 minutes
    successfulHistoryLimit: 3
    failedHistoryLimit: 1
    namespaces:
      jk:
        pipelines:
        - name: foo
          ttlSecondsAfterFinished: 60
          successfulHistoryLimit: 3
          failedHistoryLimit: 1
        - name: bar
          ttlSecondsAfterFinished: 600 # 10 minutes
          successfulHistoryLimit: 3
          failedHistoryLimit: 1
        tasks:
        - name: task1
          ttlSecondsAfterFinished: 60
      jk2:
        ttlSecondsAfterFinished: 300 # 5 minutes
        pipelines:
        - name: foo
          ttlSecondsAfterFinished: 120 # 2 minutes
  global-config: |
    ttlSecondsAfterFinished: 600 # 10 minutes
    successfulHistoryLimit: 3
    failedHistoryLimit: 1
