# Copyright 2025 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pruner-controller
  namespace: tekton-pipelines
  labels:
    pruner.tekton.dev/release: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
        pruner.tekton.dev/release: "devel"
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: controller
                topologyKey: kubernetes.io/hostname
              weight: 100

      serviceAccountName: tekton-pruner-controller
      containers:
        - name: controller
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://github.com/openshift-pipelines/tektoncd-pruner/cmd/controller
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - name: metrics
              containerPort: 9090
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging-tekton-pruner
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability-tekton-pruner
            - name: METRICS_DOMAIN
              value: pruner.tekton.dev
            - name: CONFIG_LEADERELECTION_NAME
              value: config-leader-election-tekton-pruner-controller
            # OpenTelemetry Configuration
            - name: OTEL_SERVICE_NAME
              value: tektoncd-pruner
            - name: OTEL_SERVICE_VERSION
              value: "v1.0.0"
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_PORT
              value: "9090"
            - name: PROMETHEUS_ENABLED
              value: "true"
            - name: TRACING_ENABLED
              value: "false"
            - name: OTLP_METRICS_ENABLED
              value: "false"
            - name: OTLP_TRACE_ENABLED
              value: "false"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=tektoncd-pruner,service.version=v1.0.0,service.namespace=$(SYSTEM_NAMESPACE)"
            # OTLP Configuration (uncomment and configure if using OTLP)
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://jaeger:4317"
            # - name: OTEL_EXPORTER_OTLP_INSECURE
            #   value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
            # User 65532 is the distroless nonroot user ID
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
